### ISSUE TITLE
hasPermission on Null

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark#1828]
```
2019/05/14 21:07:56 [error] 25686#25686: *41 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function hasPermissionsFor() on null in /home/circleci/builds/develop/storage/framework/views/bcdab26d8c4e8815ea6c0daae75eb924f4c58c2f.php:32
Stack trace:
#0 /home/circleci/builds/develop/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(43): include()
#1 /home/circleci/builds/develop/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/circleci/...', Array)
#2 /home/circleci/builds/develop/vendor/laravel/framework/src/Illuminate/View/View.php(142): Illuminate\View\Engines\CompilerEngine->get('/home/circleci/...', Array)
#3 /home/circleci/builds/develop/vendor/laravel/framework/src/Illuminate/View/View.php(125): Illuminate\View\View->getContents()
#4 /home/circleci/builds/develop/vendor/laravel/framework/src/Illuminate/View/View.php(90): Illuminate\View\View->renderContents()
#5 /home/circleci/builds/...
PHP message: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function hasPermissionsFor() on null in /home/circleci/builds/develop/storage/framework/views/bcdab26d8c4e8815ea6c0daae75eb924f4c58c2f.php:32
Stack trace:
#0 /home/circleci/builds/develop/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(43): include()
#1 /home/circleci/builds/develop/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/circleci/...', Array)
#2 /home/circleci/builds/develop/vendor/laravel/framework/src/Illuminate/View/View.php(142): Illuminate\View\Engines\CompilerEngine->get('/home/circleci/...', Array)
#3 /home/circleci/builds/develop/vendor/laravel/framework/src/Illuminate/View/View.php(125): Illuminate\View\View->getContents()
#4 /home/circleci/builds/develop/vendor/laravel/framework/src/Illuminate/View/View.php(90

```

500 error develop.

https://develop.spark.qa.processmaker.net

Looks related to the navbar

```
<b-navbar id="navbar" v-cloak  toggleable="md" type="light" variant="light" >
    <div class="d-flex d-block d-sm-none">
        <b-navbar-brand href="#"><img class="img-fluid" src=<?php echo e(asset(env('LOGIN_LOGO_PATH', '/img/processmaker_login.png'))); ?>></b-navbar-brand></td>
        <b-navbar-toggle target="nav_collapse"></b-navbar-toggle></td>
    </div>

    <b-collapse is-nav id="nav_collapse">
        <confirmation-modal class="d-none d-lg-block" id="confirmModal" v-if='confirmShow' :title="confirmTitle" :message="confirmMessage"
                            :variant="confirmVariant" :callback="confirmCallback"
                            @close="confirmShow=false">
        </confirmation-modal>
        <session-modal id="sessionModal" v-show='sessionShow' :title="sessionTitle" :message="sessionMessage" :time="sessionTime"
                @close="sessionShow=false">
        </session-modal>
        <div v-if="alerts.length > 0" class="alert-wrapper">
            <b-alert v-for="(item, index) in alerts" :key="index" class="d-none d-lg-block alertBox" :show="item.alertShow" :variant="item.alertVariant" dismissible fade @dismissed="alertDismissed(item)">
                {{item.alertText}}
            </b-alert>
        </div>

        <b-navbar-nav class="d-flex align-items-center">
            <?php $__currentLoopData = Menu::get('topnav')->items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                <b-nav-item href="<?php echo e($item->url()); ?>" <?php echo e($item->isActive !== false ? 'active': ''); ?>>
                    <?php echo e($item->title); ?>

                </b-nav-item>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
        </b-navbar-nav>

        <b-navbar-nav class="d-flex align-items-center ml-auto">
            <b-nav-item class="d-none d-lg-block">
                <component id="navbar-request-button" v-bind:is="'request-modal'" v-bind:permission="<?php echo e(\Auth::user()->hasPermissionsFor('processes')); ?>"></component>
            </b-nav-item>

            <b-nav-item class="d-none d-lg-block">
                <notifications id="navbar-notifications-button" v-bind:is="'notifications'" v-bind:messages="messages">
                </notifications>
            </b-nav-item>
            <b-nav-item class="seperator d-none d-lg-block"></b-nav-item>
            <li class="d-none d-lg-block">
                <?php
                    $items = [];
                    foreach ($dropdown_nav->items as $item ) {
                        $newItem = new stdClass();
                        $newItem->class = 'fas ' . $item->attr('icon') . ' fa-fw fa-lg';
                        $newItem->title = $item->title;
                        $newItem->url = $item->url();
                        $items[] = $newItem;
                    }
                    $items = json_encode($items);
                    $user = Auth::user();
                ?>
                <navbar-profile :info="<?php echo e($user); ?>"  :items="<?php echo e($items); ?>"></navbar-profile>
            </li>
        </b-navbar-nav>
    </b-collapse>
</b-navbar>
<style lang="scss" scoped>
    .seperator {
        border-right: 1px solid rgb(227, 231, 236);
        height: 30px;
    }
</style>
```

**Comment by velkymx** [comment]
This cause incomplete database migration. Solution is to run migration manually.
